## **Danubio de Araujo**

#**Trabalhando com Planilhas do Excel**

In [1]:
#Importando a biblioteca
import pandas as pd

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [7]:
#Leitura dos arquivos
df1 = pd.read_excel("/content/drive/MyDrive/datasets/Aracaju.xlsx")
df2 = pd.read_excel("/content/drive/MyDrive/datasets/Fortaleza.xlsx")
df3 = pd.read_excel("/content/drive/MyDrive/datasets/Natal.xlsx")
df4 = pd.read_excel("/content/drive/MyDrive/datasets/Recife.xlsx")
df5 = pd.read_excel("/content/drive/MyDrive/datasets/Salvador.xlsx")

In [8]:
df5.head()

     Cidade       Data  Vendas  LojaID  Qtde
0  Salvador 2018-01-01   31.06    1037     3
1  Salvador 2018-01-01   19.02    1034     3
2  Salvador 2019-02-10  173.59    1035     3
3  Salvador 2019-02-10  176.34    1037     3
4  Salvador 2019-02-14   19.47    1037     3

In [9]:
#juntando todos os arquivos
df = pd.concat([df1,df2,df3,df4,df5])

In [10]:
#Exibindo as 5 primeiras linhas
df.head()

    Cidade       Data  Vendas  LojaID  Qtde
0  Aracaju 2018-01-01  142.00    1520     1
1  Aracaju 2018-01-01   14.21    1522     6
2  Aracaju 2018-01-01   71.55    1520     1
3  Aracaju 2018-01-01    3.01    1521     7
4  Aracaju 2018-01-01   24.51    1522     8

In [11]:
#Exibindo as 5 últimas linhas
df.tail()

       Cidade       Data  Vendas  LojaID  Qtde
235  Salvador 2019-01-03   41.84    1034     1
236  Salvador 2019-01-03  126.29    1035     3
237  Salvador 2019-01-03   38.06    1036     3
238  Salvador 2019-01-03  139.64    1035     1
239  Salvador 2019-01-03  161.41    1037     3

In [12]:
df.sample(5)

        Cidade       Data  Vendas  LojaID  Qtde
53       Natal 2019-02-14  290.00     854     4
138   Salvador 2019-03-02  212.03    1037     3
236      Natal 2019-01-03  126.29    1035     3
92   Fortaleza 2019-01-01    3.49    1005     4
43      Recife 2019-01-01   22.29     983     7

In [13]:
#Verificando o tipo de dado de cada coluna
df.dtypes

Cidade            object
Data      datetime64[ns]
Vendas           float64
LojaID             int64
Qtde               int64
dtype: object

In [14]:
#Alterando o tipo de dado da coluna LojaID
df["LojaID"] = df["LojaID"].astype("object")

In [15]:
df.dtypes

Cidade            object
Data      datetime64[ns]
Vendas           float64
LojaID            object
Qtde               int64
dtype: object

In [16]:
df.head()

    Cidade       Data  Vendas LojaID  Qtde
0  Aracaju 2018-01-01  142.00   1520     1
1  Aracaju 2018-01-01   14.21   1522     6
2  Aracaju 2018-01-01   71.55   1520     1
3  Aracaju 2018-01-01    3.01   1521     7
4  Aracaju 2018-01-01   24.51   1522     8

**Tratando valores faltantes**

In [17]:
#Consultando linhas com valores faltantes
df.isnull().sum()

Cidade    0
Data      0
Vendas    0
LojaID    0
Qtde      0
dtype: int64

In [18]:
#Substituindo os valores nulos pela média
df["Vendas"].fillna(df["Vendas"].mean(), inplace=True)

In [19]:
df["Vendas"].mean()

122.61180089485438

In [20]:
df.isnull().sum()

Cidade    0
Data      0
Vendas    0
LojaID    0
Qtde      0
dtype: int64

In [21]:
df.sample(15)

        Cidade       Data  Vendas LojaID  Qtde
21      Recife 2019-01-01  164.74    983     1
107   Salvador 2019-01-01   14.70   1035     1
59   Fortaleza 2019-01-01    6.31   1002     3
87       Natal 2019-01-02  135.19   1034     2
40       Natal 2018-01-10  885.00    853     3
197   Salvador 2019-01-02   10.45   1036     2
78     Aracaju 2018-01-01  154.85   1522     9
125     Recife 2019-03-02   37.60    983     4
197      Natal 2019-01-02   10.45   1036     2
99    Salvador 2019-01-01   40.38   1037     1
195      Natal 2019-01-02   44.89   1036     3
137     Recife 2019-03-02   51.99    983     3
1      Aracaju 2018-01-01   14.21   1522     6
16       Natal 2018-07-01  298.00    854     3
54     Aracaju 2018-01-01   20.85   1523     1

In [22]:
#Substituindo os valores nulos por zero
df["Vendas"].fillna(0, inplace=True)

In [23]:
#Apagando as linhas com valores nulos
df.dropna(inplace=True)

In [24]:
#Apagando as linhas com valores nulos com base apenas em 1 coluna
df.dropna(subset=["Vendas"], inplace=True)

In [25]:
#Removendo linhas que estejam com valores faltantes em todas as colunas
df.dropna(how="all", inplace=True)

**Criando colunas novas**

In [26]:
#Criando a coluna de receita
df["Receita"] = df["Vendas"].mul(df["Qtde"])

In [27]:
df.head()

    Cidade       Data  Vendas LojaID  Qtde  Receita
0  Aracaju 2018-01-01  142.00   1520     1   142.00
1  Aracaju 2018-01-01   14.21   1522     6    85.26
2  Aracaju 2018-01-01   71.55   1520     1    71.55
3  Aracaju 2018-01-01    3.01   1521     7    21.07
4  Aracaju 2018-01-01   24.51   1522     8   196.08

In [28]:
df["Receita/Vendas"] = df["Receita"] / df["Vendas"]

In [29]:
df.head()

    Cidade       Data  Vendas LojaID  Qtde  Receita  Receita/Vendas
0  Aracaju 2018-01-01  142.00   1520     1   142.00             1.0
1  Aracaju 2018-01-01   14.21   1522     6    85.26             6.0
2  Aracaju 2018-01-01   71.55   1520     1    71.55             1.0
3  Aracaju 2018-01-01    3.01   1521     7    21.07             7.0
4  Aracaju 2018-01-01   24.51   1522     8   196.08             8.0

In [30]:
#Retornando a maior receita
df["Receita"].max()

3544.0

In [31]:
#Retornando a menor receita
df["Receita"].min()

3.34

In [32]:
#nlargest
df.nlargest(3, "Receita")

   Cidade       Data  Vendas LojaID  Qtde  Receita  Receita/Vendas
7   Natal 2019-03-18   886.0    853     4   3544.0             4.0
51  Natal 2018-01-21   859.0    852     4   3436.0             4.0
55  Natal 2019-01-08   859.0    854     4   3436.0             4.0

In [33]:
#nsamllest
df.nsmallest(3, "Receita")

      Cidade       Data  Vendas LojaID  Qtde  Receita  Receita/Vendas
118  Aracaju 2018-01-01    3.34   1522     1     3.34             1.0
65    Recife 2019-01-01    4.01    981     1     4.01             1.0
92     Natal 2019-01-02    4.57   1035     1     4.57             1.0

In [34]:
#Agrupamento por cidade
df.groupby("Cidade")["Receita"].sum()

Cidade
Aracaju       48748.25
Fortaleza     37913.97
Natal        167227.52
Recife        51936.51
Salvador      40596.73
Name: Receita, dtype: float64

In [35]:
#Ordenando o conjunto de dados
df.sort_values("Receita", ascending=False).head(10)

   Cidade       Data  Vendas LojaID  Qtde  Receita  Receita/Vendas
7   Natal 2019-03-18   886.0    853     4   3544.0             4.0
55  Natal 2019-01-08   859.0    854     4   3436.0             4.0
51  Natal 2018-01-21   859.0    852     4   3436.0             4.0
30  Natal 2018-10-02   856.0    853     4   3424.0             4.0
41  Natal 2018-05-20   835.0    852     4   3340.0             4.0
38  Natal 2018-02-25   828.0    852     4   3312.0             4.0
10  Natal 2018-10-27   828.0    852     4   3312.0             4.0
69  Natal 2019-03-24   817.0    852     4   3268.0             4.0
62  Natal 2018-02-10   793.0    854     4   3172.0             4.0
52  Natal 2018-04-27   778.0    854     4   3112.0             4.0

#**Trabalhando com datas**

In [36]:
#Trasnformando a coluna de data em tipo inteiro
df["Data"] = df["Data"].astype("int64")

In [37]:
#Verificando o tipo de dado de cada coluna
df.dtypes

Cidade             object
Data                int64
Vendas            float64
LojaID             object
Qtde                int64
Receita           float64
Receita/Vendas    float64
dtype: object

In [38]:
#Transformando coluna de data em data
df["Data"] = pd.to_datetime(df["Data"])

In [ ]:
df.dtypes

Cidade                    object
Data              datetime64[ns]
Vendas                   float64
LojaID                    object
Qtde                       int64
Receita                  float64
Receita/Vendas           float64
dtype: object

In [39]:
#Agrupamento por ano
df.groupby(df["Data"].dt.year)["Receita"].sum()

Data
2018    118176.53
2019    228246.45
Name: Receita, dtype: float64

In [40]:
#Criando uma nova coluna com o ano
df["Ano_Venda"] = df["Data"].dt.year

In [ ]:
df.sample(5)

       Cidade       Data  Vendas  ... Receita  Receita/Vendas  Ano_Venda
124  Salvador 2019-03-02   44.82  ...  134.46             3.0       2019
218  Salvador 2019-01-02  189.12  ...  567.36             3.0       2019
82    Aracaju 2018-01-01  150.48  ...  601.92             4.0       2018
29   Salvador 2019-01-01    9.27  ...    9.27             1.0       2019
123  Salvador 2019-03-02  127.45  ...  382.35             3.0       2019

[5 rows x 8 columns]

In [41]:
#Extraindo o mês e o dia
df["mes_venda"], df["dia_venda"] = (df["Data"].dt.month, df["Data"].dt.day)

In [42]:
df.sample(5)

        Cidade       Data  Vendas  ... Ano_Venda  mes_venda  dia_venda
4     Salvador 2019-02-14   19.47  ...      2019          2         14
239      Natal 2019-01-03  161.41  ...      2019          1          3
89   Fortaleza 2019-01-01    7.19  ...      2019          1          1
21     Aracaju 2018-01-01   37.36  ...      2018          1          1
112   Salvador 2019-03-02   43.00  ...      2019          3          2

[5 rows x 10 columns]

In [43]:
#Retornando a data mais antiga
df["Data"].min()

Timestamp('2018-01-01 00:00:00')

In [44]:
#Calculando a diferença de dias
df["diferenca_dias"] = df["Data"] - df["Data"].min()

In [45]:
df.sample(5)

        Cidade       Data  Vendas  ... mes_venda  dia_venda  diferenca_dias
130     Recife 2019-03-02   12.36  ...         3          2        425 days
35   Fortaleza 2019-01-01  133.97  ...         1          1        365 days
1        Natal 2018-11-25  563.00  ...        11         25        328 days
100   Salvador 2019-01-01  190.97  ...         1          1        365 days
13     Aracaju 2018-01-01   43.45  ...         1          1          0 days

[5 rows x 11 columns]

In [46]:
#Criando a coluna de trimestre
df["trimestre_venda"] = df["Data"].dt.quarter

In [47]:
df.sample(5)

        Cidade       Data  Vendas  ... dia_venda  diferenca_dias  trimestre_venda
18    Salvador 2019-01-01  242.31  ...         1        365 days                1
84   Fortaleza 2019-01-01  147.46  ...         1        365 days                1
23     Aracaju 2018-01-01  237.50  ...         1          0 days                1
70       Natal 2019-02-14  743.00  ...        14        409 days                1
135      Natal 2019-01-02    9.95  ...         2        366 days                1

[5 rows x 12 columns]

In [49]:
#Filtrando as vendas de 2019 do mês de março
vendas_marco_19 = df.loc[(df["Data"].dt.year == 2019) & (df["Data"].dt.month == 3)]

In [50]:
vendas_marco_19.sample(20)

        Cidade       Data  Vendas  ... dia_venda  diferenca_dias  trimestre_venda
124  Fortaleza 2019-03-02   47.98  ...         2        425 days                1
110     Recife 2019-03-02   51.98  ...         2        425 days                1
111   Salvador 2019-03-02  147.35  ...         2        425 days                1
5        Natal 2019-03-30  674.00  ...        30        453 days                1
109     Recife 2019-03-02   18.90  ...         2        425 days                1
29       Natal 2019-03-09  646.00  ...         9        432 days                1
126     Recife 2019-03-02   41.87  ...         2        425 days                1
139     Recife 2019-03-02  141.16  ...         2        425 days                1
130   Salvador 2019-03-02   59.78  ...         2        425 days                1
116  Fortaleza 2019-03-02   79.10  ...         2        425 days                1
115   Salvador 2019-03-02  202.33  ...         2        425 days                1
116     Recife 2019-03-02   79.10  ...         2        425 days                1
134     Recife 2019-03-02  195.18  ...         2        425 days                1
124   Salvador 2019-03-02   44.82  ...         2        425 days                1
131  Fortaleza 2019-03-02  139.07  ...         2        425 days                1
111  Fortaleza 2019-03-02    8.00  ...         2        425 days                1
115  Fortaleza 2019-03-02   12.23  ...         2        425 days                1
114     Recife 2019-03-02   16.82  ...         2        425 days                1
32       Natal 2019-03-17  244.00  ...        17        440 days                1
129   Salvador 2019-03-02  125.66  ...         2        425 days                1

[20 rows x 12 columns]